### ISSUE TITLE
Merge the latest working version

### ISSUE THREAD

**Issue by ipa-nhg** [squirrel-project/squirrel_planning#64]
Hi! 

I am currently checking the status of all the squirrel repositories and squirrel_planning is out-of-date and broken. I can't build it because it is not synced with squirrel_common.

@Morloth1274 could you please send a PR with the updated version of squirrel_planning and squirrel_common?? @edith-langer @tpatten @mzillich  the current installed version on robotino is also ok. I show you have several branches with merge conflicts and don't know which is the right one.

It is quite urgent! Thanks!

**Comment by tpatten** [comment]
Hi Nadia, the version of squirrel_planning is the same as what @Morloth1274 pushed to his repository after the integration meting in January. @Morloth1274, which branch is this in your fork? Since January we have made no changes.

**Comment by ipa-nhg** [comment]
Thanks @tpatten . I found this one https://github.com/squirrel-project/squirrel_planning/pull/63 but the manipulation messages are old and not supported since we migrate to the new planning driver...

**Comment by tpatten** [comment]
That pull request is very old. I don't think that @Morloth1274 has made a PR with the updates from January.

**Comment by ipa-nhg** [comment]
ok! probably this commit is the last one:  https://github.com/Morloth1274/squirrel_planning/commit/f7953cdaeafa1a3307647aacd33ad180ced4f299

Lets see if this version can be built with the latest squirrel_common version!

**Comment by tpatten** [comment]
Hi Nadia,

The latest version that we have on our robot is this one: https://github.com/Morloth1274/squirrel_planning/commit/607867f887e4eb402d6f5fc2eb9707add7aa796f, but it seems it doesn't build according to the PR https://github.com/squirrel-project/squirrel_planning/pull/63

**Comment by ipa-nhg** [comment]
Yep, no idea which version is the right one.... I sent an email to @Morloth1274 

@tpatten Thanks for your help!

**Comment by Morloth1274** [comment]
I will look into it tonight.

**Comment by Morloth1274** [comment]
So the behaviour-and-emotions branch is the most up-to-date. It seems you tried to pull that version but the code for the squirrel-interface-manipulation does not match what is on that branch, somehow. I will investigate further.

**Comment by Morloth1274** [comment]
Tried to compile the version we tested in Vienna and get this error message. Does anyone knows what it is about?

Errors << squirrel_classification:cmake /home/bram/projects/squirrel/logs/squirrel_classification/build.cmake.007.log                                                                                       
V4R_INCLUDE_DIRS:/usr/share/V4R/3rdparty/include/usr/include
CMake Error at /usr/share/V4R/V4RDependencies.cmake:43 (add_library):
  Cannot find source file:

    INTERFACE

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
Call Stack (most recent call first):
  /usr/share/V4R/V4RDependencies.cmake:130 (v4r_add_imported_library)
  /usr/share/V4R/V4RConfig.cmake:79 (include)
  CMakeLists.txt:9 (find_package)


CMake Error in CMakeLists.txt:
  Cannot find source file:

    IMPORTED

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


CMake Error in CMakeLists.txt:
  Cannot find source file:

    GLOBAL

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


CMake Warning (dev) in CMakeLists.txt:
  Policy CMP0022 is not set: INTERFACE_LINK_LIBRARIES defines the link
  interface.  Run "cmake --help-policy CMP0022" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  Target "boost" has an INTERFACE_LINK_LIBRARIES property.  This should be
  preferred as the source of the link interface for this library but because
  CMP0022 is not set CMake is ignoring the property and using the link
  implementation as the link interface instead.

  INTERFACE_LINK_LIBRARIES:

    /usr/lib/x86_64-linux-gnu/libboost_thread.so;/usr/lib/x86_64-linux-gnu/libboost_program_options.so;/usr/lib/x86_64-linux-gnu/libboost_serialization.so;/usr/lib/x86_64-linux-gnu/libboost_system.so;/usr/lib/x86_64-linux-gnu/libboost_filesystem.so;/usr/lib/x86_64-linux-gnu/libboost_regex.so;/usr/lib/x86_64-linux-gnu/libpthread.so

  Link implementation:

    (empty)

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in CMakeLists.txt:
  Policy CMP0022 is not set: INTERFACE_LINK_LIBRARIES defines the link
  interface.  Run "cmake --help-policy CMP0022" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  Target "opencv" has an INTERFACE_LINK_LIBRARIES property.  This should be
  preferred as the source of the link interface for this library but because
  CMP0022 is not set CMake is ignoring the property and using the link
  implementation as the link interface instead.

  INTERFACE_LINK_LIBRARIES:

    opencv_videostab;opencv_video;opencv_superres;opencv_stitching;opencv_photo;opencv_ocl;opencv_objdetect;opencv_ml;opencv_legacy;opencv_imgproc;opencv_highgui;opencv_gpu;opencv_flann;opencv_features2d;opencv_core;opencv_contrib;opencv_calib3d;opencv_videostab;opencv_video;opencv_superres;opencv_stitching;opencv_photo;opencv_ocl;opencv_objdetect;opencv_ml;opencv_legacy;opencv_imgproc;opencv_highgui;opencv_gpu;opencv_flann;opencv_features2d;opencv_core;opencv_contrib;opencv_calib3d

  Link implementation:

    (empty)

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in CMakeLists.txt:
  Policy CMP0022 is not set: INTERFACE_LINK_LIBRARIES defines the link
  interface.  Run "cmake --help-policy CMP0022" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  Target "pcl" has an INTERFACE_LINK_LIBRARIES property.  This should be
  preferred as the source of the link interface for this library but because
  CMP0022 is not set CMake is ignoring the property and using the link
  implementation as the link interface instead.

  INTERFACE_LINK_LIBRARIES:

    /usr/lib/x86_64-linux-gnu/libboost_system.so;/usr/lib/x86_64-linux-gnu/libboost_filesystem.so;/usr/lib/x86_64-linux-gnu/libboost_thread.so;/usr/lib/x86_64-linux-gnu/libboost_date_time.so;/usr/lib/x86_64-linux-gnu/libboost_iostreams.so;/usr/lib/x86_64-linux-gnu/libboost_serialization.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/libpcl_common.so;/usr/lib/libpcl_octree.so;/usr/lib/libOpenNI.so;vtkCommon;vtkRendering;vtkHybrid;vtkCharts;/usr/lib/libpcl_io.so;/usr/lib/x86_64-linux-gnu/libflann_cpp_s.a;/usr/lib/libpcl_kdtree.so;/usr/lib/libpcl_search.so;/usr/lib/libpcl_sample_consensus.so;/usr/lib/libpcl_filters.so;/usr/lib/libpcl_features.so;/usr/lib/libpcl_keypoints.so;/usr/lib/libpcl_segmentation.so;/usr/lib/libpcl_visualization.so;/usr/lib/libpcl_outofcore.so;/usr/lib/libpcl_registration.so;/usr/lib/libpcl_recognition.so;/usr/lib/x86_64-linux-gnu/libqhull.so;/usr/lib/libpcl_surface.so;/usr/lib/libpcl_people.so;/usr/lib/libpcl_tracking.so;/usr/lib/libpcl_apps.so

  Link implementation:

    (empty)

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in CMakeLists.txt:
  Policy CMP0022 is not set: INTERFACE_LINK_LIBRARIES defines the link
  interface.  Run "cmake --help-policy CMP0022" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  Target "opengl" has an INTERFACE_LINK_LIBRARIES property.  This should be
  preferred as the source of the link interface for this library but because
  CMP0022 is not set CMake is ignoring the property and using the link
  implementation as the link interface instead.

  INTERFACE_LINK_LIBRARIES:

    GL

  Link implementation:

    (empty)

This warning is for project developers.  Use -Wno-dev to suppress it.

cd /home/bram/projects/squirrel/build/squirrel_classification; catkin build --get-env squirrel_classification | catkin env -si  /usr/bin/cmake /home/bram/projects/squirrel/src/squirrel_perception/squirrel_classification --no-warn-unused-cli -DCATKIN_DEVEL_PREFIX=/home/bram/projects/squirrel/devel/.private/squirrel_classification -DCMAKE_INSTALL_PREFIX=/home/bram/projects/squirrel/install; cd -
............................................................................................................................................................................................................
Failed << squirrel_classification:cmake                            [ Exited with code 1 ]                                                                                                                   
bram@Bram-Laptop:~/projects/squirrel$

**Comment by ipa-nhg** [comment]
Thanks @Morloth1274 . See this comment https://github.com/squirrel-project/squirrel_planning/pull/63#issuecomment-369505605

The error you get is because of the v4r library version. do you know which one do you have installed? @edith-langer can you help Bram?

I think this should work:

```
wget http://153.97.4.193/building/ubuntu/pool/main/v/v4r/v4r_1.4.9-0trusty_amd64.deb
sudo dpkg -i v4r_1.4.9-0trusty_amd64.deb
```

**Comment by tpatten** [comment]
Any progress? We are starting the integration week and need to run the full scenario as soon as possible.

**Comment by ipa-nhg** [comment]
Almost done! https://github.com/squirrel-project/squirrel_planning/pull/68 I am waiting for the CI servers to merge the PR.

**Comment by ipa-nhg** [comment]
squirrel_planning is updated and passed all the tests, please use the upstream version squirrel-project/indigo_dev

Thanks for your support

**Comment by Morloth1274** [comment]
Great, thanks!
